### ISSUE TITLE
リンク色が見えづらい

### ISSUE THREAD

**Issue by pklion** [kazuhito-m/youkai-password-challenge#20]
あらすじなどの文章を読んでいると、リンクの色がとても見えづらく感じます。
#1976d2 → #49a6e2 くらい明るければ見やすいかと。

(参考)
![image](https://user-images.githubusercontent.com/78145811/150631556-51d1cb39-2c96-4bbb-9a0e-aa5bb6e4a597.png)
![image](https://user-images.githubusercontent.com/78145811/150631580-e7e8601d-2a22-4963-bf06-b91c93565a6c.png)

**Comment by kazuhito-m** [comment]
@pklion 
ありがとうございます。
ご助言通り、アンカーのベース色を変更したいと思います。
